(()=>{const scroll=id=>setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'}),80);document.addEventListener('click',e=>{const a=e.target.closest('a[href="#popular"],a[href="#categories"]');if(!a)return;e.preventDefault();const id=a.getAttribute('href').slice(1);if(location.hash!=='#home')location.hash='#home';scroll(id)});})();

// Product update patch: remove four tools and provide Word-to-PDF upload support.
(()=>{
const removed=new Set(['currency-converter','remove-background','pdf-to-word','percentage-calculator']);
const allowed=()=>TOOLS.filter(t=>!removed.has(t.id));
const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function card2(t){return `<a class="tool-card" href="#tool/${t.id}"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p><span class="tag">100% FREE</span></a>`}
function tools2(q=''){const s=q.toLowerCase(),a=allowed().filter(t=>!s||`${t.name} ${t.cat}`.toLowerCase().includes(s));app.innerHTML=`<section class="section"><div class="section-head"><div><h1>All Free Tools</h1><p>${a.length} tools available.</p></div></div><div class="search" style="max-width:760px;margin:0 0 20px"><input id="q" value="${esc2(q)}" placeholder="Search tools…"><button class="btn" id="go">Search</button></div><div class="tool-grid">${a.length?a.map(card2).join(''):'<div class="tool-card"><h3>No tools found</h3><p>Try another search.</p></div>'}</div></section>`;$('#go').onclick=()=>location.hash='search/'+encodeURIComponent($('#q').value)}
function home2(){const a=allowed();app.innerHTML=`<section class="hero"><span class="eyebrow">✦ ${a.length} free tools · No signup</span><h1>Free online tools for <span class="gradient-text">everyday tasks.</span></h1><p>Calculators, PDF tools, converters and text utilities. Every tool is free to use.</p><div class="search"><input id="q" placeholder="Search a tool…" aria-label="Search tools"><button class="btn" id="go">Search</button></div><div class="free-pill">✓ 100% free · No ads right now · No account required</div></section><section class="section" id="popular"><div class="section-head"><div><h2>Popular tools</h2><p>Quick access to everyday favorites.</p></div><a class="btn secondary" href="#tools">All tools</a></div><div class="tool-grid">${a.slice(0,8).map(card2).join('')}</div></section><section class="section" id="categories"><div class="section-head"><div><h2>Categories</h2><p>Find tools by purpose.</p></div></div><div class="category-grid">${[...new Set(a.map(t=>t.cat))].map(c=>`<a class="category" href="#category/${encodeURIComponent(c)}"><strong>${c}</strong><span>${a.filter(t=>t.cat===c).length} free tools</span></a>`).join('')}</div></section>`;$('#go').onclick=()=>location.hash='search/'+encodeURIComponent($('#q').value)}
function word2(t){page(t,`<div class="field"><label>Text</label><textarea id="txt" placeholder="Start typing…"></textarea></div><div class="stats"><div class="stat"><b id="w">0</b>Words</div><div class="stat"><b id="c">0</b>Characters</div></div><div class="result" id="read">Reading time: 0 min</div>`);$('#txt').oninput=()=>{const v=$('#txt').value.trim(),w=v?v.split(/\s+/).length:0;$('#w').textContent=w;$('#c').textContent=$('#txt').value.length;$('#read').textContent=`Reading time: ${w?Math.max(1,Math.ceil(w/200)):0} min`}}
async function wordPdf2(t){page(t,`<div class="tool-tabs"><button class="tab active" data-mode="type">Type / Paste</button><button class="tab" data-mode="upload">Upload Word</button></div><div id="typed"><div class="field"><label>Document text</label><textarea id="text" placeholder="Type or paste your document text…"></textarea></div></div><div id="uploaded" hidden><div class="dropzone" id="drop"><strong>Select a Word document</strong><p>Upload a .docx file and convert its readable text to PDF.</p><input id="f" class="hidden" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></div></div><div class="actions"><button class="btn" id="run">Create PDF</button></div><div class="result" id="out">Choose typing or Word upload.</div>`);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const up=b.dataset.mode==='upload';$('#typed').hidden=up;$('#uploaded').hidden=!up});$('#drop')?.addEventListener('click',()=>$('#f').click());$('#run').onclick=async()=>{try{let text=$('#text')?.value||'',f=$('#f')?.files?.[0];if(f){if(!f.name.toLowerCase().endsWith('.docx'))return toast('Please choose a .docx Word document');if(!window.JSZip)await lib('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js');const z=await JSZip.loadAsync(await f.arrayBuffer()),file=z.file('word/document.xml');if(!file)return toast('Invalid Word document');const xml=await file.async('string'),doc=new DOMParser().parseFromString(xml,'application/xml');text=[...doc.getElementsByTagName('w:t')].map(n=>n.textContent).join(' ').replace(/\s+/g,' ').trim();if(!text)return toast('No readable text found in the Word document.')}if(!text.trim())return toast('Type/paste text or upload a Word document');const J=await jsPDF(),d=new J(),lines=d.splitTextToSize(text,170);let y=20;for(const line of lines){if(y>280){d.addPage();y=20}d.text(line,20,y);y+=7}d.save('document.pdf');$('#out').textContent=f?'Word document converted to PDF.':'PDF created.'}catch(e){console.error(e);$('#out').textContent='Could not convert this document. Please check the file and try again.'}}}
function route2(){const h=location.hash.slice(1)||'home',p=h.split('/'),v=decodeURIComponent(p.slice(1).join('/'));if(h==='home')home2();else if(h==='tools')tools2();else if(h==='about')about();else if(p[0]==='search')tools2(v);else if(p[0]==='category')tools2(v);else if(p[0]==='tool'){if(removed.has(v)){location.hash='#tools';return}const t=allowed().find(x=>x.id===v);if(!t){app.innerHTML='<section class="tool-page"><h1>Tool not found</h1><a class="btn" href="#tools">All tools</a></section>';return}if(v==='word-counter')word2(t);else if(v==='word-to-pdf')wordPdf2(t);else render(t)}else home2()}
window.addEventListener('hashchange',route2);route2();
})();
